### ISSUE TITLE
Connection to Search Server Failed

### ISSUE THREAD

**Issue by ryuu9** [soruly/whatanime.ga#6]
when i try it, its say "Connection to Search Server Failed" how to fix it? thanks

**Comment by soruly** [comment]
What browser are you using?

**Comment by soruly** [comment]
@ryuu9 oh did you clone this repo and run this on your server?

**Comment by ryuu9** [comment]
yes. i clone and run it. do i miss somwthing?

**Comment by soruly** [comment]
Under the section [how does it work](https://github.com/soruly/whatanime.ga#how-does-it-work) , you may found all the other components and scripts that makes the whole system work.
Because of licensing problems, I can't include everything in this repo. So it may be a bit challenging for you to setup the whole thing.

If video reverse search is the only thing you want, the orange parts (in the diagram System Overview) are what you need. This repo only contains codes on whatanime.ga

**Comment by soruly** [comment]
Closed due to inactivity
