### ISSUE TITLE
There was no problem about 1 week ago

### ISSUE THREAD

**Issue by Fireman733** [soruly/whatanime.ga#9]
But now the anime search on this site is so very inaccurate

**Comment by soruly** [comment]
Do you have a few sample images I cound test?

**Comment by soruly** [comment]
https://github.com/soruly/whatanime.ga/commit/0504ba290fe41986e63d30a878fb4c322eb2e548#diff-42f69825340f0b5fa628d80900a46daaR218

About a week ago, I've moved the search iteration from server side to client side. This changes the target match similarly from 90% to 87% . So it may stop digging for result once it has found a similarly one. This is because you can now click "keep searching", in case you didn't find any match in first trial. 

But I do notice the same thing when I use it myself, 87% similarly is likely not the original scene.
I'll raise it back to 90% to see how it goes.

**Comment by Fireman733** [comment]
Ahh ok Thank You i think it's better now
